---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: argo
  namespace: ${releaseNamespace}
spec:
  interval: 10m
  timeout: 1m
  url: https://argoproj.github.io/argo-helm
---