---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gadget
  namespace: ${releaseNamespace}
spec:
  interval: 10m
  timeout: 1m
  url: https://inspektor-gadget.github.io/charts
---