---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openfga
  namespace: ${releaseNamespace}
spec:
  interval: 10m
  timeout: 1m
  url: https://openfga.github.io/helm-charts
---