---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openfga
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: openfga
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openfga
        namespace: ${releaseNamespace}
      version: 0.2.23
  interval: 1m0s
  targetNamespace: ${releaseNamespace}
  releaseName: openfga
  valuesFrom:
    - kind: ConfigMap
      name: openfga-0.2.23-defaults
    - kind: ConfigMap
      name: openfga-overrides
      optional: true