---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: policy-reporter
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: policy-reporter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: policy-reporter
        namespace: ${releaseNamespace}
      version: 3.0.4
  interval: 1m0s
  targetNamespace: ${releaseNamespace}
  releaseName: policy-reporter
  valuesFrom:
    - kind: ConfigMap
      name: policy-reporter-3.0.4-defaults
    - kind: ConfigMap
      name: policy-reporter-overrides
      optional: true