---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: meshery
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: meshery
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: meshery
        namespace: ${releaseNamespace}
      version: 0.8.36
  interval: 1m0s
  targetNamespace: ${releaseNamespace}
  releaseName: meshery
  valuesFrom:
    - kind: ConfigMap
      name: meshery-0.8.36-defaults
    - kind: ConfigMap
      name: meshery-overrides
      optional: true