---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-json-exporter
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: prometheus-json-exporter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: ${releaseNamespace}
      version: 0.16.0
  interval: 1m0s
  targetNamespace: ${releaseNamespace}
  releaseName: prometheus-json-exporter
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-json-exporter-0.16.0-defaults
    - kind: ConfigMap
      name: prometheus-json-exporter-overrides
      optional: true