---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: trust-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: ${releaseNamespace}
      version: 0.16.0
  interval: 1m0s
  targetNamespace: ${releaseNamespace}
  releaseName: trust-manager
  valuesFrom:
    - kind: ConfigMap
      name: trust-manager-0.16.0-defaults
    - kind: ConfigMap
      name: trust-manager-overrides
      optional: true