---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opencost
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: opencost
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: opencost
        namespace: ${releaseNamespace}
      version: 1.43.2
  interval: 1m0s
  targetNamespace: ${releaseNamespace}
  releaseName: opencost
  valuesFrom:
    - kind: ConfigMap
      name: opencost-1.43.2-defaults
    - kind: ConfigMap
      name: opencost-overrides
      optional: true