---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dns-operator
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: dns-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kuadrant
        namespace: ${releaseNamespace}
      version: 0.13.0-alpha1
  interval: 1m0s
  targetNamespace: ${releaseNamespace}
  releaseName: dns-operator
  valuesFrom:
    - kind: ConfigMap
      name: dns-operator-0.13.0-alpha1-defaults
    - kind: ConfigMap
      name: dns-operator-overrides
      optional: true