---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: ${releaseNamespace}
      version: 69.4.1
  interval: 1m0s
  targetNamespace: ${releaseNamespace}
  releaseName: kube-prometheus-stack
  valuesFrom:
    - kind: ConfigMap
      name: kube-prometheus-stack-69.4.1-defaults
    - kind: ConfigMap
      name: kube-prometheus-stack-overrides
      optional: true