---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-csi-driver
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: cert-manager-csi-driver
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: ${releaseNamespace}
      version: 0.10.2
  interval: 1m0s
  targetNamespace: ${releaseNamespace}
  releaseName: cert-manager-csi-driver
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-csi-driver-0.10.2-defaults
    - kind: ConfigMap
      name: cert-manager-csi-driver-overrides
      optional: true