---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-adapter
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: prometheus-adapter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: ${releaseNamespace}
      version: 4.11.0
  interval: 1m0s
  targetNamespace: ${releaseNamespace}
  releaseName: prometheus-adapter
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-adapter-4.11.0-defaults
    - kind: ConfigMap
      name: prometheus-adapter-overrides
      optional: true