---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prom-label-proxy
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: prom-label-proxy
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: ${releaseNamespace}
      version: 0.10.1
  interval: 1m0s
  targetNamespace: ${releaseNamespace}
  releaseName: prom-label-proxy
  valuesFrom:
    - kind: ConfigMap
      name: prom-label-proxy-0.10.1-defaults
    - kind: ConfigMap
      name: prom-label-proxy-overrides
      optional: true