---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-approver-policy
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: cert-manager-approver-policy
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: ${releaseNamespace}
      version: 0.19.0
  interval: 1m0s
  targetNamespace: ${releaseNamespace}
  releaseName: cert-manager-approver-policy
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-approver-policy-0.19.0-defaults
    - kind: ConfigMap
      name: cert-manager-approver-policy-overrides
      optional: true