---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: ${releaseNamespace}
spec:
  interval: 10m
  timeout: 1m
  url: https://charts.jetstack.io
---