---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-csi-driver-spiffe
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: cert-manager-csi-driver-spiffe
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: ${releaseNamespace}
      version: 0.8.2
  interval: 1m0s
  targetNamespace: ${releaseNamespace}
  releaseName: cert-manager-csi-driver-spiffe
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-csi-driver-spiffe-0.8.2-defaults
    - kind: ConfigMap
      name: cert-manager-csi-driver-spiffe-overrides
      optional: true