---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno-policies
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: kyverno-policies
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: ${releaseNamespace}
      version: 3.3.4
  interval: 1m0s
  targetNamespace: ${releaseNamespace}
  releaseName: kyverno-policies
  valuesFrom:
    - kind: ConfigMap
      name: kyverno-policies-3.3.4-defaults
    - kind: ConfigMap
      name: kyverno-policies-overrides
      optional: true