---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: artifact-hub
  namespace: ${releaseNamespace}
spec:
  interval: 10m
  timeout: 1m
  url: https://artifacthub.github.io/helm-charts/
---