---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubewarden-controller
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: kubewarden-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kubewarden
        namespace: ${releaseNamespace}
      version: 4.1.0
  interval: 1m0s
  targetNamespace: ${releaseNamespace}
  releaseName: kubewarden-controller
  valuesFrom:
    - kind: ConfigMap
      name: kubewarden-controller-4.1.0-defaults
    - kind: ConfigMap
      name: kubewarden-controller-overrides
      optional: true