---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubewarden
  namespace: ${releaseNamespace}
spec:
  interval: 10m
  timeout: 1m
  url: https://charts.kubewarden.io
---