---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: open-feature-operator
  namespace: ${releaseNamespace}
spec:
  interval: 10m
  timeout: 1m
  url: https://open-feature.github.io/open-feature-operator
---