---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-istio-csr
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: cert-manager-istio-csr
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: ${releaseNamespace}
      version: 0.14.0
  interval: 1m0s
  targetNamespace: ${releaseNamespace}
  releaseName: cert-manager-istio-csr
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-istio-csr-0.14.0-defaults
    - kind: ConfigMap
      name: cert-manager-istio-csr-overrides
      optional: true