---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-blackbox-exporter
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: ${releaseNamespace}
      version: 9.2.0
  interval: 1m0s
  targetNamespace: ${releaseNamespace}
  releaseName: prometheus-blackbox-exporter
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-blackbox-exporter-9.2.0-defaults
    - kind: ConfigMap
      name: prometheus-blackbox-exporter-overrides
      optional: true