---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: headlamp
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: ${releaseNamespace}
      version: 0.28.1
  interval: 1m0s
  targetNamespace: ${releaseNamespace}
  releaseName: headlamp
  valuesFrom:
    - kind: ConfigMap
      name: headlamp-0.28.1-defaults
    - kind: ConfigMap
      name: headlamp-overrides
      optional: true