---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: headlamp
  namespace: ${releaseNamespace}
spec:
  interval: 10m
  timeout: 1m
  url: https://headlamp-k8s.github.io/headlamp/
---