---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-conntrack-stats-exporter
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: prometheus-conntrack-stats-exporter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: ${releaseNamespace}
      version: 0.5.16
  interval: 1m0s
  targetNamespace: ${releaseNamespace}
  releaseName: prometheus-conntrack-stats-exporter
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-conntrack-stats-exporter-0.5.16-defaults
    - kind: ConfigMap
      name: prometheus-conntrack-stats-exporter-overrides
      optional: true