---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keptn
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: keptn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: lifecycle-toolkit
        namespace: ${releaseNamespace}
      version: 0.10.0
  interval: 1m0s
  targetNamespace: ${releaseNamespace}
  releaseName: keptn
  valuesFrom:
    - kind: ConfigMap
      name: keptn-0.10.0-defaults
    - kind: ConfigMap
      name: keptn-overrides
      optional: true