---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: openebs
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: ${releaseNamespace}
      version: 4.2.0
  interval: 1m0s
  targetNamespace: ${releaseNamespace}
  releaseName: openebs
  valuesFrom:
    - kind: ConfigMap
      name: openebs-4.2.0-defaults
    - kind: ConfigMap
      name: openebs-overrides
      optional: true