---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openebs
  namespace: ${releaseNamespace}
spec:
  interval: 10m
  timeout: 1m
  url: https://openebs.github.io/openebs
---