---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubewarden-defaults
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: kubewarden-defaults
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kubewarden
        namespace: ${releaseNamespace}
      version: 2.8.1
  interval: 1m0s
  targetNamespace: ${releaseNamespace}
  releaseName: kubewarden-defaults
  valuesFrom:
    - kind: ConfigMap
      name: kubewarden-defaults-2.8.1-defaults
    - kind: ConfigMap
      name: kubewarden-defaults-overrides
      optional: true