---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubewarden-crds
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: kubewarden-crds
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kubewarden
        namespace: ${releaseNamespace}
      version: 1.13.0
  interval: 1m0s
  targetNamespace: ${releaseNamespace}
  releaseName: kubewarden-crds
  valuesFrom:
    - kind: ConfigMap
      name: kubewarden-crds-1.13.0-defaults
    - kind: ConfigMap
      name: kubewarden-crds-overrides
      optional: true