---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kuadrant-operator
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: kuadrant-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kuadrant
        namespace: ${releaseNamespace}
      version: 1.1.0-alpha1
  interval: 1m0s
  targetNamespace: ${releaseNamespace}
  releaseName: kuadrant-operator
  valuesFrom:
    - kind: ConfigMap
      name: kuadrant-operator-1.1.0-alpha1-defaults
    - kind: ConfigMap
      name: kuadrant-operator-overrides
      optional: true