---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argocd-image-updater
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: argocd-image-updater
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: ${releaseNamespace}
      version: 0.12.0
  interval: 1m0s
  targetNamespace: ${releaseNamespace}
  releaseName: argocd-image-updater
  valuesFrom:
    - kind: ConfigMap
      name: argocd-image-updater-0.12.0-defaults
    - kind: ConfigMap
      name: argocd-image-updater-overrides
      optional: true