---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argo-events
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: argo-events
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: ${releaseNamespace}
      version: 2.4.13
  interval: 1m0s
  targetNamespace: ${releaseNamespace}
  releaseName: argo-events
  valuesFrom:
    - kind: ConfigMap
      name: argo-events-2.4.13-defaults
    - kind: ConfigMap
      name: argo-events-overrides
      optional: true